spring.application.name=ProgettoWeb
spring.datasource.url=jdbc:postgresql://localhost:5432/VenditaImmobili
spring.datasource.username=postgres
spring.datasource.password=123456
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true

