spring.application.name=ProgettoWeb

spring.datasource.url=jdbc:postgresql://localhost:5432/venditaImmobili
spring.datasource.username=postgres
spring.datasource.password=123456
spring.datasource.driver-class-name=org.postgresql.Driver

spring.flyway.enabled=true
spring.flyway.locations=classpath:db.migration

logging.level.org.springframework.jdbc.core=DEBUG
