spring.application.name=ProgettoWeb


# Configurazione Postgres
spring.datasource.url=jdbc:postgresql://localhost:5432/VenditaImmobiliare
spring.datasource.username=postgres
spring.datasource.password=123456
spring.datasource.driver-class-name=org.postgresql.Driver


# FA VEDERE LE QUERY NELLA CONSOLE ED é SOLO PER IL DEBUG
logging.level.org.springframework.jdbc.core=DEBUG