ALTER TABLE public.users ADD COLUMN "isBanned" BOOLEAN NOT NULL DEFAULT FALSE;
ALTER TABLE public.sellers ADD COLUMN "isBanned" BOOLEAN NOT NULL DEFAULT FALSE;

ALTER TABLE public.posts ADD COLUMN "transactionType" VARCHAR(20) NOT NULL DEFAULT 'VENDITA';

ALTER TABLE public.posts ADD COLUMN "isAuction" BOOLEAN NOT NULL DEFAULT FALSE;
ALTER TABLE public.posts ADD COLUMN "auctionEndTime" TIMESTAMP NULL;